### ISSUE TITLE
Can't change modes reliably?

### ISSUE THREAD

**Issue by FailurePoint** [wnew/fencing_scoring_box#18]
Hello there, I am interested in build an implementation of this for my local club and was toying around with the code and a breadboard this evening and decided to do it.
However, I am having a ton of issues, I can not seem to get [simulated] touches to register (unless connecting A0, A1, A2 to each other all at once which lights up both Hit lights) and the mode change button will not change modes.
I get the "Mode Changed: #" message in serial but it just repeats the same mode number unless I press it really fast for a while then eventually it will shift to the next mode...
Now, I admit this is partial circuit texting on a breadboard, but what might be wrong??
The mode button should not be dependent on any other systems besides the connection to pin 2 and ground right?
the only thing omitted from my test circuit was the pull around (up and down) resistors on the A0-A5 pins which I did hook up afterward but quite likely incorrectly.

any help understanding what is wrong is appropriated. I am not new to electronics but C has also never been my strongest language.

I can't understand about half the code here.

My board is an Arduino Uno with possible RF damage to it from being to close to some high power radio equipment in my lab. In case that makes a difference since I think some of the functions in the code use pretty sensitive parts of the board.  

Thanks in advance.

**Comment by wnew** [comment]
Hi @FailurePoint I trust that you came right, if not please open a new issue. Ill be releasing an updated version of the code and schematics in the coming weeks.
