### ISSUE TITLE
Foil Depress Timing

### ISSUE THREAD

**Issue by wnew** [wnew/fencing_scoring_box#3]
This foil depress timing doesnt work. This needs to be investigated and a solution found.

**Comment by digitalWestie** [comment]
Any idea on how we accurately measure this?

**Comment by wnew** [comment]
I have yet to investigate this properly. The foil hit seems to trigger even if the tip is depressed for less then 14ms. This makes me think that the loop isnt looping quickly enough to check the value on the pin again within the 14ms. Which is worrying as it should be looping more then once in 1ms if we want accurate timing measurements.

**Comment by wnew** [comment]
After some basic testing it seems that the loop can take anywhere from .5ms to 3ms. This is an average taken over 10000 loops. This wont be good enough to run a fencing box and probably means that the whole thing needs to be redesigned. :(

one more thing to try is to comment out the serial println statements as these slow down the code dramatically.

**Comment by digitalWestie** [comment]
Oh no! Which firmware was tested?

**Comment by wnew** [comment]
Tested the Foilbox and the allweaponsbox.

But it isnt as bad as I initially thought. I removed al the delays and serial prints and the average seems to stick around 0.5ms. So we can make it work. But I still need to figure out why the foil is triggering for hits with a depression of 1ms.

**Comment by digitalWestie** [comment]
Yes, I imagined the serial prints would take up some time. Btw, which board
are you running this on?

Not too well read on the standard 'loop' speed etc but I came across this
post which might be handy:  http://www.paleotechnologist.net/?p=1808

**Comment by wnew** [comment]
Sorry I dropped the ball on this one. I am getting back into this design and will look into the problem again. That link is pretty cool. Ill try and implement some of the optimisations it suggests.

I am running this on an Uno. With the idea to change to a pro mini at a later stage. Another option though is to run it on a Due and then we dont need to worry about optimisations. Although then it wont be as portable as I would have liked.

**Comment by wnew** [comment]
This has been fixed by a full overhaul of the foil algorithm. Yah!!

**Comment by digitalWestie** [comment]
omg well done! Does it just work on Due? Or other platforms?

**Comment by wnew** [comment]
So it wont port to directly to the due right now. The issue is that the due is 3v3 and the ADC values that the code looks for are relative to 5v. This should not be too hard to do though. I am happy that the Uno/Nano and Pro mini (5v) can all sample the ADCs fast enough to catch all required touches. :)

If you have time, could you try to implement it. I would love to have someone else's feedback.
