### ISSUE TITLE
Project finished?

### ISSUE THREAD

**Issue by Dyason** [wnew/fencing_scoring_box#4]
Is this considered fully working now? Have you used it much? I was thinking of building a fencing scoring box based on this and wondered if the accuracy was solid now.

**Comment by wnew** [comment]
I am finally happy that the foil and epee boxes are working correctly, I just need to test sabre. I have done a lot of lab testing to ensure that the timings are accurate. Using an oscilloscope as well as simulated hits. I am planning to release it into the wild in the next week or 2. Yay!
