### ISSUE TITLE
any video?

### ISSUE THREAD

**Issue by aloknand** [wnew/fencing_scoring_box#5]
HI. Have you made any video on demonstration of how this works? i'm trying to make one

**Comment by wnew** [comment]
Not yet, but I have updated the boxes and will get some as soon as I am able to test a box in a real bout. :)

**Comment by senjabl** [comment]
I tested it and it worked OK. I don't have reels, so we tried with borrowed ones.

**Comment by wnew** [comment]
Senjabl, you built this scoring machine? It would be great to see some pictures.

**Comment by senjabl** [comment]
No, it is on hold.  I am assembling 3d printer. 
In the end, I will probably abandon WiFi wersion due to instability.It  works perfectly with wires. 
On the other hand, I am working on spools similar to Favero, only homememade. That's why I need 3D printer.
If I get somewhere I will publish it..

**Comment by senjabl** [comment]
This is photo of my version. It is running on two arduinos. 
First one is running hits and lights with your FW, and another is in charge for remote, clock, cards and score.

![img_20160228_195639](https://cloud.githubusercontent.com/assets/9935967/13381188/ce947110-de55-11e5-9717-c7852e8bc8c4.jpg)

**Comment by Solexis2001** [comment]
Wow, wonderfull. I like the fact you engraved or drew or whatever the logo on the box.
 Is it possible to see the code of the sabre part (sorry, that's the only weapon I practice and the most forgotten one by the DIYselfers) and could you give an explaination of the circuit you designed around the arduino (the one that runs the hits of course ;-).
If so, my adress (and my many many thanks by anticpiation) : solex@hotmail.com.
And if not, no prob, I just tried ;-)

**Comment by wnew** [comment]
> This is photo of my version. It is running on two arduinos. 
> First one is running hits and lights with your FW, and another is in charge for remote, clock, cards and score.

Amazing work.

**Comment by wnew** [comment]
@Solexis2001 The Sabre code can be found at https://github.com/wnew/fencing_scoring_box/blob/master/firmware/sabrebox/sabrebox.ino

Is it also integrated into the AllWeaponBox at https://github.com/wnew/fencing_scoring_box/blob/master/firmware/allweaponbox/allweaponbox.ino The functionality is in the sabre() method.

It is still untested. I hope to find time to test it this week.

**Comment by senjabl** [comment]
@Solexis2001, sorry but I did not test it with sabre. We do only floret (foil) and epee. 
Anyway code you can find on 
https://github.com/wnew/fencing_scoring_box/blob/master/firmware/allweaponbox/allweaponbox.ino

**Comment by wnew** [comment]
@senjabl Are you able to share your code and circuit?

**Comment by senjabl** [comment]
@wnew I am little bit lazy, so I don't have some nice documentation.
I promise I will share it as soon as I catch some time. You know that phrase "Born to fence, forced to work...". 
Anyway, your firmware is so good, thank you.

**Comment by wnew** [comment]
@senjabl Haha, I know the feeling. :) Looking forward to seeing your work.

Thanks

**Comment by Solexis2001** [comment]
Sorry Senjabl, I didn't realize your box was based on Wnew's code. My bad :-)

**Comment by bhupilm** [comment]
Can anyone send a video how to make

**Comment by dreamersx** [comment]
Could you please explain how to code and connect the mode lights?

**Comment by wnew** [comment]
Check out line 48 of the allweapon box 
const uint8_t modeLeds[] = {4, 5, 6}; // LED pins to indicate weapon mode selected {f e s}
https://github.com/wnew/fencing_scoring_box/blob/master/firmware/allweaponbox/allweaponbox.ino

You just need to connect and LED in series with a resistor from each of these pins to ground.

Also note that I use the scoring lights to signal Foil Epee and Sabre modes as well.
See the function setModeLeds() in the same file
