### ISSUE TITLE
Provide better documentation

### ISSUE THREAD

**Issue by wnew** [wnew/fencing_scoring_box#6]
The documentation needs to be good enough that someone can easily assemble a working prototype.

Readmes and clear specs

**Comment by senjabl** [comment]
This is interesting project. Can you give me any clue about resistor values used in circuit?

**Comment by wnew** [comment]
Hi Senjabi,

The resistor values dont make a big difference, as long as they are all the same value. They just act as voltage dividers. I would recommend 10k although I have used 220R before.

**Comment by wnew** [comment]
An istructable has been put together, see http://www.instructables.com/id/Arduino-Fencing-Scoring-Apparatus/
